name: Docker Image CI

on:
  schedule:
    - cron: 0 0 * * 6
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    container: neuralegion/devops

    strategy:
      matrix:
        package:
          - chromium
          - chromium-headful
          - chrome

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=result::$(make --file ${{ matrix.package }}/Makefile get-version)

      - name: Build image
        run: make --file ${{ matrix.package }}/Makefile build version=${{ steps.get_version.outputs.result }}

      - name: Login into Docker
        run: docker login --username=anatol1988 --password=${{ secrets.DOCKER_TOKEN }}

      - name: Push image to Docker
        run: docker push neuralegion/nextools-${{ matrix.package }}

      - name: Push Docker image to AWS ECR
        run: docker push 454884832027.dkr.ecr.us-east-1.amazonaws.com/nextools-${{ matrix.package }}

